<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>StreamDockSDK</RootNamespace>

        <PackageId>StreamDockSDK</PackageId>
        <Version>1.0.0</Version>
        <Authors>Sejtam_</Authors>
        <RepositoryUrl>https://github.com/sejtam-dev/SteamDockSDK</RepositoryUrl>
        <PackageProjectUrl>https://github.com/sejtam-dev/SteamDockSDK</PackageProjectUrl>
        <PackageTags>StreamDock SDK Plugin Development Hardware Controller Automation</PackageTags>
        <Description>
            C# SDK for StreamDock plugins development.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="log4net" Version="3.2.0"/>
    </ItemGroup>
    
    <ItemGroup>
        <!-- ProjectReference automatically becomes PackageReference dependency in NuGet -->
        <ProjectReference Include="..\StreamDockSDK.Attributes\StreamDockSDK.Attributes.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Embed log4net.config as embedded resource for fallback -->
        <EmbeddedResource Include="Assets\log4net.config"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Include MSBuild targets for automatic manifest generation -->
        <None Include="Build\StreamDockSDK.targets" Pack="true" PackagePath="build\$(PackageId).targets" />
    </ItemGroup>


</Project>
