<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>StreamDockSDK.Attributes</RootNamespace>

        <PackageId>StreamDockSDK.Attributes</PackageId>
        <Version>1.0.0</Version>
        <Authors>Sejtam_</Authors>
        <RepositoryUrl>https://github.com/sejtam-dev/SteamDockSDK</RepositoryUrl>
        <PackageProjectUrl>https://github.com/sejtam-dev/SteamDockSDK</PackageProjectUrl>
        <PackageTags>StreamDock SDK Attributes Plugin Development</PackageTags>
        <Description>
            Attributes for StreamDock plugin manifest generation.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.2" />
    </ItemGroup>

</Project>
